version: '3.8'

services:
  # 1. Kontainer Aplikasi (Flask + Gunicorn/Python)
  sinergi-app:
    build: .
    container_name: sinergi_v16_app
    expose:
      - "5000"
    volumes:
      # JALUR TOL: Menghubungkan semua kode di folder VPS ke dalam Docker
      - .:/app 
      # Tetap pertahankan volume untuk data agar aman
      - ./instance:/app/instance
      - ./static/uploads:/app/static/uploads
    environment:
      # Ubah ke development agar fitur 'Auto-Reload' Flask aktif saat ada update kode
      - FLASK_ENV=development 
      - PYTHONUNBUFFERED=1
    restart: always

  # 2. Kontainer Nginx (Si Satpam Pintu Depan)
  nginx-proxy:
    image: nginx:alpine
    container_name: sinergi_v16_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static/uploads:/app/static/uploads:ro
    depends_on:
      - sinergi-app
    restart: always
