server {
    listen 80;
    server_name localhost;

    # 1. Buka jalur tanpa batas untuk upload file raksasa (1GB+)
    client_max_body_size 0; 

    # 2. Perpanjang nafas Nginx (Timeout) sampai 30 menit
    # Sangat penting agar tidak muncul '504 Gateway Timeout' saat cicil 1jt data
    proxy_read_timeout 1800;
    proxy_connect_timeout 1800;
    proxy_send_timeout 1800;

    location / {
        proxy_pass http://sinergi-app:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Tambahan agar Nginx tidak memutus koneksi secara sepihak
        proxy_buffering off;
        proxy_request_buffering off;
    }

    # Akses langsung foto kunjungan (High Speed)
    location /static/uploads/ {
        alias /app/static/uploads/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
